### ISSUE TITLE
Discussion on souping for text classification models fine-tuned from DistilBERT

### ISSUE THREAD

**Issue by sayakpaul** [mlfoundations/model-soups#5] opened 2022-11-03 03:40 UTC
Hi there. 

I followed Cade's Colab Notebook and thought of expanding it to text classification models. So, to do that, I first fine-tuned five models (with different hyperparameters) on the text classification task with DistilBERT [1].

I am observing interesting results. This is how the individual models perform (which I believe is not different from what's shown in Cade's notebook):

![image](https://user-images.githubusercontent.com/22957388/199643147-66469ac3-e1ec-42f1-b2af-291142e2282c.png)

These are the raw scores:

```py
{'distilbert-base-uncased-finetuned-emotion-lr-0.0003-wd-003': 0.9335,
 'distilbert-base-uncased-finetuned-emotion-lr-3e-05-wd-001': 0.919,
 'distilbert-base-uncased-finetuned-emotion-lr-2e-05-wd-0001': 0.896,
 'distilbert-base-uncased-finetuned-emotion-lr-0.0006-wd-0003': 0.8875,
 'distilbert-base-uncased-finetuned-emotion-lr-1e-05-wd-0002': 0.7495}
```

With uniform souping, I get:

![image](https://user-images.githubusercontent.com/22957388/199643195-1171445a-bd9a-4e37-a456-0efb2fb70388.png)

Perform drop is quite drastic with it. I understand there can be a myriad of reasons for this. But wanted to know if you have observed something similar in your experiments. 

This is the utility I am using for souping:

```py
def get_souped_model(state_dicts):
    new_state_dict = {}
    state_dict_keys = list(state_dicts[0].keys())

    for k in state_dict_keys:
        temp_weights = []
        for state_dict in state_dicts:
            temp_weights.append(state_dict[k].cpu())

        stacked_weights = torch.stack(temp_weights)
        averaged_weights = torch.mean(stacked_weights, dim=0)

        new_state_dict.update({k: averaged_weights})

    model = AutoModelForSequenceClassification.from_pretrained(model_ckpt, num_labels=6)
    model.load_state_dict(new_state_dict)
    return model.to(device)
```

With greedy souping, only the best model survives. 

I have open-sourced my code here: https://github.com/sayakpaul/model-soups-text-classification.

Looking forward to your thoughts.

**Comment by mitchellnw** [comment] 2022-11-03 04:19
Hello! I'm not to familiar with Cade's notebook but I do have some thoughts on why this may be happening. Specifically my guess is that the issue is one of two things:

1. Starting out with a bad model when fine-tuning. In our paper we examine two different ways to initialize the model before fine-tuning: a) zero-shot, and b) LP-FT. In the former, we start out with a "zero-shot" model which already has okay performance on the task. In the latter, we follow this paper: https://arxiv.org/abs/2202.10054 and first train a classification layer (backbone frozen). Then, when fine-tuning end-to-end we initialize all models with that classification layer. For the text clf experiments in the paper, we do sometimes see 0 improvement which means that the greedy soup just selects the single best model -- as we say: the improvements are not as pronounced as in image classification. Still, this drop that you're seeing seems much larger than what we've seen so this is my guess. For the text classification exps in the paper we use "zero-shot" by starting with T5 (so no new params are introduces when fine-tuning).

2. One bug we ran into when averaging the NLP models was tied embedding and final layer, which was causing issues when we averaged due to in-place operations. Looking at your code I don't think this is an issue but tagging my co-author @gabrielilharco to see if he has thoughts since he was the one who fixed this bug!

**Comment by sayakpaul** [comment] 2022-11-03 04:30
Sorry, this is [notebook](https://colab.research.google.com/drive/1UmK-phTRXC4HoKb7_rScawnRqlG82svF?usp=sharing) I was referring to. I found out about it from the repo README. 

Thanks for providing the inputs. The Colab Notebook shows the CIFAR-10 results and do you by chance know if the checkpoints were obtained using LP-FT? 

Maybe I will try LP-FT and see if that improves the performance.

**Comment by mitchellnw** [comment] 2022-11-03 05:18
Oh yea I mean I do know about Cade's notebook just not the details. I can't remember if Cade is using zero-shot init or LP-FT but I know 100% that notebook is using one of those two. My guess is LP-FT will do the trick, using a common LP for all of the FTs.

**Comment by sayakpaul** [comment] 2022-11-03 06:05
Nice. I will give it a try and report my findings. 

Soups are really interesting and has got a lot of value for a practitioner I think.

**Comment by mitchellnw** [comment] 2022-11-03 19:11
Closing, feel free to re-open.

**Closed as completed by mitchellnw** 2022-11-03 19:11 UTC
